const leaflets = [
  {
    'leaflet-code': null,
    'operation': 'Operation Desert Shield',
    'conflict': 'The Gulf War',
    'year': '1990-1991',
    'country-theater': 'Iraq / Kuwait theater',
    'languages': ['Arabic'],
    'translation': 'This site is being bombed!',
    'objective': 'The leaflet aims to create immediate panic and disorder by notifying Iraqi forces that their location is under attack, compelling them to abandon their posts.',
    'imagery': 'A stark line drawing of an F-117 stealth fighter dropping bombs on an Iraqi airfield, with soldiers fleeing the scene.',
    'message-type': 'Air-strike warning',
    'target-audience': 'Iraqi soldiers at a targeted site',
    'call-to-action': 'Abandon the position and flee',
    'key-figures-symbols': ['F-117 aircraft', 'bombs', 'airfield', 'fleeing soldiers'],
    'catalog-number': '4',
  },
  {
    'leaflet-code': null,
    'operation': 'Operation Desert Shield',
    'conflict': 'The Gulf War',
    'year': '1990-1991',
    'country-theater': 'Iraq / Kuwait theater',
    'languages': ['Arabic'],
    'translation': 'Saddam is the only reason to bomb Iraq!',
    'objective': 'The leaflet attempts to instill a sense of betrayal among Iraqi soldiers, urging them to recognize Saddam Hussein as the reason for the bombing and devastation in Iraq. The visual portrayal of blood on the flag underlines the human cost of his leadership.',
    'imagery': 'A bloodied Iraqi flag is juxtaposed with a cartoonish depiction of Saddam Hussein, reinforcing the message that he is the sole cause of the nation\'s suffering.',
    'message-type': 'Anti-regime blame message',
    'target-audience': 'Iraqi soldiers and civilians',
    'call-to-action': 'Blame Saddam Hussein for the bombing',
    'key-figures-symbols': ['Saddam Hussein', 'Iraqi flag', 'blood splatter'],
    'catalog-number': '6',
  },
  {
    'leaflet-code': null,
    'operation': 'Operation Desert Shield',
    'conflict': 'The Gulf War',
    'year': '1990-1991',
    'country-theater': 'Iraq / Kuwait theater',
    'languages': ['Arabic'],
    'translation': 'My brother, the Iraqi soldier, it pains us deeply that you would return to Iraq either killed or disabled',
    'objective': 'The leaflet aims to confront Iraqi soldiers with the harsh realities of war, stressing that continuing to fight will likely result in death or severe injury. The emotional appeal is designed to break the resolve of soldiers and prompt them to surrender.',
    'imagery': 'A colored depiction of an Iraqi soldier envisioning his fate on the battlefield and the potential consequences of returning home either dead or disabled.',
    'message-type': 'Casualty deterrence',
    'target-audience': 'Iraqi soldiers',
    'call-to-action': 'Stop fighting to avoid death or disability',
    'key-figures-symbols': ['Iraqi soldier', 'battlefield', 'family', 'injury'],
    'catalog-number': '14',
  },
  {
    'leaflet-code': 'C21',
    'operation': 'Operation Desert Shield',
    'conflict': 'The Gulf War',
    'year': '1990-1991',
    'country-theater': 'Iraq / Kuwait theater',
    'languages': ['Arabic'],
    'translation': 'If you want to save your life, follow these steps: Remove the ammunition magazine from your weapon. Raise your weapon above your head with your left hand. Place the weapon on the ground gently, with the barrel pointed down. To ensure your safety, keep your hands raised above your head and move slowly toward the designated safe area, where the flag of peace is displayed. You are welcome here.',
    'objective': 'This leaflet is a practical guide for Iraqi soldiers on how to surrender safely. It aims to reduce resistance by making the process of surrendering clear and straightforward, reassuring soldiers that they will be treated humanely if they follow the instructions.',
    'imagery': 'The leaflet provides a step-by-step guide with illustrations on how to safely surrender to coalition forces, showing a soldier following these steps.',
    'message-type': 'Safe-conduct instructions',
    'target-audience': 'Iraqi soldiers',
    'call-to-action': 'Disarm, raise your hands, and surrender safely',
    'key-figures-symbols': ['Weapon magazine', 'raised hands', 'peace flag', 'family thought bubble'],
    'catalog-number': '30',
  },
  {
    'leaflet-code': null,
    'operation': 'Operation Desert Shield',
    'conflict': 'The Gulf War',
    'year': '1990-1991',
    'country-theater': 'Iraq / Kuwait theater',
    'languages': ['Arabic'],
    'translation': 'Listen to Radio Kuwait on FM frequencies 92.5, 97.5, 87.9, and 98.8 MHz.',
    'objective': 'The leaflet is intended to direct the Iraqi population and soldiers to listen to Radio Kuwait, which likely broadcasts coalition propaganda and information, aiming to sway public opinion and lower morale among Iraqi forces.',
    'imagery': 'The leaflet features a simple drawing of a radio antenna with a list of FM frequencies alongside the emblem of Kuwait.',
    'message-type': 'Radio broadcast directive',
    'target-audience': 'Iraqi soldiers and civilians',
    'call-to-action': 'Tune in to Radio Kuwait on the listed FM frequencies',
    'key-figures-symbols': ['Radio set', 'Kuwait emblem', 'FM frequencies'],
    'catalog-number': '32',
  },
  {
    'leaflet-code': '1-W',
    'operation': 'Operation Desert Shield',
    'conflict': 'The Gulf War',
    'year': '1990-1991',
    'country-theater': 'Iraq / Kuwait theater',
    'languages': [],
    'translation': 'No printed front text on the leaflet; image-only front.',
    'objective': 'This leaflet aims to symbolize a potential alliance or peaceful relations between Iraq and Saudi Arabia. It suggests a future where cooperation replaces conflict, encouraging Iraqi forces and citizens to consider a peaceful resolution.',
    'imagery': 'The leaflet depicts the flags of Iraq and Saudi Arabia with two figures shaking hands, set against the backdrop of a rising sun.',
    'message-type': 'Symbolic unity appeal',
    'target-audience': 'Iraqi soldiers and civilians',
    'call-to-action': 'Accept peaceful cooperation with Saudi Arabia',
    'key-figures-symbols': ['Iraqi flag', 'Saudi flag', 'handshake', 'rising sun'],
    'catalog-number': '40',
  },
  {
    'leaflet-code': 'CIA3',
    'operation': 'Operation Desert Storm',
    'conflict': 'The Gulf War',
    'year': '1991',
    'country-theater': 'Iraq / Kuwait theater',
    'languages': ['Arabic'],
    'translation': 'We can live for 20 years. But our warehouses are empty, and your warehouses are full.',
    'objective': 'This leaflet aims to highlight the harsh realities faced by Iraqi citizens under Saddam\'s rule, contrasting the regime\'s empty promises with the visible suffering of the people. It seeks to undermine the morale of Iraqi soldiers by showing the stark difference between what they are told and the actual living conditions.',
    'imagery': 'The leaflet depicts a military figure standing confidently, surrounded by poorly dressed and malnourished children, emphasizing the disparity between the promises of the regime and the actual conditions.',
    'message-type': 'Scarcity and hardship message',
    'target-audience': 'Iraqi civilians',
    'call-to-action': 'Recognize the regime\'s shortages and deprivations',
    'key-figures-symbols': ['Civilian figure', 'empty warehouses', 'scarcity'],
    'catalog-number': '71',
  },
  {
    'leaflet-code': null,
    'operation': 'Operation Inherent Resolve',
    'conflict': 'The Iraq War',
    'year': '2014-present',
    'country-theater': 'Iraq / Syria theater',
    'languages': ['Arabic'],
    'translation': 'ISIS robs our boys of their childhood... and turns them into murderers.',
    'objective': 'The leaflet condemns ISIS for turning children into murderers, urging the protection of their innocence.',
    'imagery': 'A split image showing a young boy being forced to execute someone and a group of children playing, contrasting innocence with corruption.',
    'message-type': 'Anti-ISIS child-protection message',
    'target-audience': 'Iraqi and Syrian civilians',
    'call-to-action': 'Protect children from ISIS recruitment and violence',
    'key-figures-symbols': ['Armed child', 'schoolchildren', 'split-screen comparison'],
    'catalog-number': '286',
  },
  {
    'leaflet-code': null,
    'operation': 'Operation Inherent Resolve',
    'conflict': 'The Iraq War',
    'year': '2014-present',
    'country-theater': 'Iraq / Syria theater',
    'languages': ['Arabic'],
    'translation': 'For any oppressor there is an end.',
    'objective': 'To emphasize the inevitability of defeat for oppressors and to bolster the morale of anti-ISIS forces.',
    'imagery': 'A Kurdish fighter shooting an ISIS militant, symbolizing the defeat of oppression.',
    'message-type': 'Anti-ISIS inevitability message',
    'target-audience': 'ISIS fighters and affected civilians',
    'call-to-action': 'Understand that every oppressor comes to an end',
    'key-figures-symbols': ['Armed silhouette', 'map outline', 'Syrian Democratic Forces text'],
    'catalog-number': '292',
  },
  {
    'leaflet-code': null,
    'operation': 'Operation Inherent Resolve',
    'conflict': 'The Iraq War',
    'year': '2014-present',
    'country-theater': 'Iraq / Syria theater',
    'languages': ['Arabic'],
    'translation': 'Stay away from these locations during coalition strikes. Fighting positions for Da\'esh. Da\'esh check points. Coalition forces realize you are victims of Da\'esh terror by using you as human shields.',
    'objective': 'To warn civilians to avoid specific locations used by ISIS, as they are targets for coalition strikes.',
    'imagery': 'A map with highlighted danger zones and images of ISIS fighters in these areas.',
    'message-type': 'Strike warning',
    'target-audience': 'Civilians near ISIS positions',
    'call-to-action': 'Stay away from ISIS checkpoints and fighting positions',
    'key-figures-symbols': ['ISIS flags', 'checkpoint', 'hazard symbol', 'flames'],
    'catalog-number': '305',
  },
  {
    'leaflet-code': 'IZ D019',
    'operation': 'Operation Iraqi Freedom',
    'conflict': 'The Iraq War',
    'year': '2003-2011',
    'country-theater': 'Iraq',
    'languages': ['Arabic'],
    'translation': 'Do not use weapons of mass destruction.',
    'objective': 'The leaflet warns against the use of weapons of mass destruction, highlighting the severe consequences that would follow, including retaliation from coalition forces.',
    'imagery': 'A dramatic image of soldiers in gas masks against a backdrop of an explosion, with a prominent biohazard symbol, conveying the danger of using such weapons.',
    'message-type': 'WMD deterrence',
    'target-audience': 'Iraqi military personnel',
    'call-to-action': 'Do not use weapons of mass destruction',
    'key-figures-symbols': ['Biohazard symbol', 'gas masks', 'fireball'],
    'catalog-number': '189',
  },
  {
    'leaflet-code': 'IZ D038',
    'operation': 'Operation Iraqi Freedom',
    'conflict': 'The Iraq War',
    'year': '2003-2011',
    'country-theater': 'Iraq',
    'languages': ['Arabic'],
    'translation': 'Iraq. We can see everything. Do not use nuclear, biological, or chemical weapons.',
    'objective': 'The leaflet is a warning to the Iraqi military, emphasizing that coalition forces are monitoring their activities and urging them not to use nuclear, biological, or chemical weapons.',
    'imagery': 'An image of a satellite observing military activities on the ground, with text in Arabic cautioning against the use of specific weapons.',
    'message-type': 'WMD surveillance warning',
    'target-audience': 'Iraqi military personnel',
    'call-to-action': 'Do not use nuclear, biological, or chemical weapons',
    'key-figures-symbols': ['Satellite', 'Iraq map', 'missile', 'chemical barrel'],
    'catalog-number': '194',
  },
  {
    'leaflet-code': null,
    'operation': 'Operation Iraqi Freedom',
    'conflict': 'The Iraq War',
    'year': '2003-2011',
    'country-theater': 'Iraq',
    'languages': ['Arabic'],
    'translation': 'Return to your home! Your families are waiting for you!',
    'objective': 'To encourage Iraqi citizens to return to their homes and reunite with their families, emphasizing the importance of family ties.',
    'imagery': 'A woman holding a child, looking longingly, likely representing a mother waiting for her family to return home.',
    'message-type': 'Return-home appeal',
    'target-audience': 'Iraqi soldiers and civilians in combat areas',
    'call-to-action': 'Go home and reunite with your families',
    'key-figures-symbols': ['Bombers overhead', 'family waiting', 'return-home message'],
    'catalog-number': '201',
  },
  {
    'leaflet-code': 'IZ D041a',
    'operation': 'Operation Iraqi Freedom',
    'conflict': 'The Iraq War',
    'year': '2003-2011',
    'country-theater': 'Iraq',
    'languages': ['Arabic'],
    'translation': 'This is what the leaflets say: "You will be destroyed if you target coalition aircraft."',
    'objective': 'The leaflet warns that any attempt to target coalition aircraft will result in destruction. It is a direct threat to discourage attacks on coalition forces.',
    'imagery': 'Two men standing in front of a tank with leaflets raining down, with planes flying overhead.',
    'message-type': 'Air-defense deterrence',
    'target-audience': 'Iraqi military personnel',
    'call-to-action': 'Do not target coalition aircraft',
    'key-figures-symbols': ['Coalition aircraft', 'leaflets falling', 'armored vehicles', 'warning speech bubble'],
    'catalog-number': '212',
  },
  {
    'leaflet-code': 'IZ D005',
    'operation': 'Operation Iraqi Freedom',
    'conflict': 'The Iraq War',
    'year': '2003-2011',
    'country-theater': 'Iraq',
    'languages': ['Arabic'],
    'translation': 'Take an aggressive position and you will be destroyed.',
    'objective': 'The leaflet warns the enemy that if they continue their aggression, they will face inevitable destruction, emphasizing the futility of resistance.',
    'imagery': 'The leaflet displays two panels. The left panel shows a tank engulfed in flames, with two fighter jets attacking from above, symbolizing destruction. The right panel shows a fully intact tank with aircraft flying overhead, symbolizing the enemy\'s power.',
    'message-type': 'Destruction warning',
    'target-audience': 'Iraqi armored units',
    'call-to-action': 'Do not take an aggressive position',
    'key-figures-symbols': ['Destroyed tank', 'intact tank', 'strike aircraft'],
    'catalog-number': '220',
  },
  {
    'leaflet-code': null,
    'operation': 'Operation Iraqi Freedom',
    'conflict': 'The Iraq War',
    'year': '2003-2011',
    'country-theater': 'Iraq',
    'languages': ['Arabic'],
    'translation': 'Throwing stones is dangerous! When a child throws stones at coalition vehicles, this may be misunderstood by the soldiers as an offensive act that results in them being injured or killed. For the safety of everyone, no one should throw stones at vehicles and transporters of the coalition forces.',
    'objective': 'It warns that throwing stones at coalition vehicles is dangerous and could be misunderstood as an offensive act, leading to injury or death. It emphasizes the importance of not throwing stones for everyone\'s safety.',
    'imagery': 'The leaflet depicts children and a warning about throwing stones.',
    'message-type': 'Civilian conduct warning',
    'target-audience': 'Iraqi children and civilians',
    'call-to-action': 'Do not throw stones at coalition vehicles',
    'key-figures-symbols': ['Children', 'stones', 'coalition vehicles', 'warning text'],
    'catalog-number': '257',
  },
  {
    'leaflet-code': 'IZG8539a',
    'operation': 'Operation Iraqi Freedom',
    'conflict': 'The Iraq War',
    'year': '2003-2011',
    'country-theater': 'Iraq',
    'languages': ['Arabic'],
    'translation': 'Throwing rocks is dangerous. It may be fun to throw rocks at Coalition Forces\' vehicles, but this could cause injury to coalition soldiers or injuries to you. Coalition Forces are authorized to arrest any person throwing rocks or participating in any other dangerous activities.',
    'objective': 'It warns that throwing rocks at Coalition Forces\' vehicles could cause injury to soldiers or to the person throwing the rock. It emphasizes that the Coalition Forces are authorized to arrest anyone engaging in such dangerous activities.',
    'imagery': 'The leaflet discusses the dangers of throwing rocks.',
    'message-type': 'Civilian conduct warning',
    'target-audience': 'Iraqi children and civilians',
    'call-to-action': 'Stop throwing rocks at coalition forces',
    'key-figures-symbols': ['Children', 'vehicle', 'rock-throwing', 'arrest warning'],
    'catalog-number': '258',
  },
  {
    'leaflet-code': 'IZG7527',
    'operation': 'Operation Iraqi Freedom',
    'conflict': 'The Iraq War',
    'year': '2003-2011',
    'country-theater': 'Iraq',
    'languages': ['Arabic'],
    'translation': 'No matter where you run, no matter where you hide, Coalition Special Operations Forces will find you and bring you to justice.',
    'objective': 'To intimidate and demoralize the opposition by conveying that they cannot escape the coalition\'s pursuit and justice.',
    'imagery': 'A close-up of eyes watching, symbolizing surveillance and the reach of coalition forces, with text asserting that the enemy will be found and brought to justice.',
    'message-type': 'Manhunt intimidation',
    'target-audience': 'Wanted insurgents and armed opponents',
    'call-to-action': 'Do not run or hide; coalition forces will find you',
    'key-figures-symbols': ['Eyes', 'fear', 'special operations threat'],
    'catalog-number': '265',
  },
  {
    'leaflet-code': 'IZ D023',
    'operation': 'Operation Iraqi Freedom',
    'conflict': 'The Iraq War',
    'year': '2003-2011',
    'country-theater': 'Iraq',
    'languages': ['Arabic'],
    'translation': 'Stay at home with your families in safety and peace.',
    'objective': 'Encourage Iraqi citizens to stay at home with their families to ensure safety and peace during the ongoing conflict.',
    'imagery': 'A family sitting together in their home, suggesting a peaceful environment.',
    'message-type': 'Stay-at-home safety message',
    'target-audience': 'Iraqi civilians',
    'call-to-action': 'Stay at home with your families',
    'key-figures-symbols': ['Family meal', 'domestic interior', 'peace and safety'],
    'catalog-number': '282',
  },
  {
    'leaflet-code': 'LY11H01IILF0001',
    'operation': 'Operation Odyssey Dawn',
    'conflict': 'The Libyan Civil War',
    'year': '2011',
    'country-theater': 'Libya',
    'languages': ['English'],
    'translation': 'Help Has Arrived! Spread the word amongst all who will listen and tell all that the coalition forces are conducting military operations in order to bring the peace that the people deserve.',
    'objective': 'The leaflet aims to encourage the population to spread the word that coalition forces are conducting military operations to bring peace.',
    'imagery': 'A crowd of people waving flags and celebrating, with the text "Help Has Arrived!" displayed prominently.',
    'message-type': 'Coalition reassurance message',
    'target-audience': 'Libyan civilians',
    'call-to-action': 'Spread the word that coalition action is meant to bring peace',
    'key-figures-symbols': ['Crowd scene', 'flags', 'celebratory gathering'],
    'catalog-number': '308',
  },
  {
    'leaflet-code': 'AF D16g',
    'operation': 'Operation Enduring Freedom',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2014',
    'country-theater': 'Afghanistan',
    'languages': [],
    'translation': 'No printed front text on the leaflet; image-only front.',
    'objective': 'The leaflet aims to inform the local population about the distribution of humanitarian daily rations (HDR) and encourage them to pick up and use the aid being provided.',
    'imagery': 'The leaflet shows an Afghan man picking up a leaflet from the ground with the label "HDR." On the right side, a large military aircraft is depicted dropping leaflets over a barren landscape.',
    'message-type': 'Humanitarian aid notice',
    'target-audience': 'Afghan civilians',
    'call-to-action': 'Collect and use humanitarian daily rations',
    'key-figures-symbols': ['C-17 aircraft', 'falling leaflets', 'HDR packets', 'Afghan man'],
    'catalog-number': '136',
  },
  {
    'leaflet-code': 'AFD69b',
    'operation': 'Operation Enduring Freedom',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2014',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'In your graves?',
    'objective': 'The leaflet intends to reinforce the message of inevitable doom for those who continue to associate with Al-Qaeda, suggesting that their actions will lead them to death and destruction.',
    'imagery': 'The same group of Afghan men is now in a state of panic inside the cave. An explosion has occurred, filling the cave with smoke and debris. The men are depicted as frightened, covering their heads with their hands, realizing the dire consequences of their actions.',
    'message-type': 'Fear appeal',
    'target-audience': 'al-Qaeda and Taliban fighters in hiding',
    'call-to-action': 'Do not believe you are safe in hiding',
    'key-figures-symbols': ['Cave', 'meal on rug', 'trapped fighters', 'rubble'],
    'catalog-number': '139',
  },
  {
    'leaflet-code': 'AF D29n',
    'operation': 'Operation Enduring Freedom',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2014',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'Award up to 25 million dollars. Osama bin Laden',
    'objective': 'The leaflet\'s goal is to encourage people to provide information leading to the capture of Osama bin Laden by offering a substantial financial reward.',
    'imagery': 'The leaflet displays two images of Osama bin Laden, one where he is giving a speech and another showing him behind bars, implying his capture. Between the images is a stack of U.S. dollar bills, highlighting the reward amount.',
    'message-type': 'Reward offer',
    'target-audience': 'Afghan civilians and informants',
    'call-to-action': 'Provide information on Osama bin Laden for a reward',
    'key-figures-symbols': ['Osama bin Laden', 'U.S. dollars', 'prison bars', 'reward arrow'],
    'catalog-number': '140',
  },
  {
    'leaflet-code': null,
    'operation': 'Operation Enduring Freedom',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2014',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'It is falling now! Bin Laden Haqqani Mutawakil',
    'objective': 'To convey the imminent downfall of the Taliban and encourage individuals to distance themselves from the group or take action against it.',
    'imagery': 'The same three figures (Bin Laden, Haqqani, and Mutawakkil) are depicted, but this time their faces are altered to appear as skulls, symbolizing the fall of the Taliban regime.',
    'message-type': 'Regime-collapse message',
    'target-audience': 'Afghan civilians and Taliban supporters',
    'call-to-action': 'Recognize that Taliban leadership is falling',
    'key-figures-symbols': ['Bin Laden', 'Haqqani', 'Mutawakil', 'skull faces'],
    'catalog-number': '145',
  },
  {
    'leaflet-code': 'AF G2001',
    'operation': 'Operation Enduring Freedom',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2014',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto'],
    'translation': 'Coalition forces are looking for Al-Qaeda members and other terrorists. If you are aware of their plans or terrorist activities, report them to these locations. Do it: To a member of the Navy. To coalition embassies. US Awards program for Justice (0118008773927). By phone number or email (mail@dssrewards.net). Your identity will be protected, and your family will be protected.',
    'objective': 'To gather intelligence from local populations about terrorist activities, assuring them that their identities will be protected.',
    'imagery': 'The leaflet shows a coalition soldier interacting with locals, along with information on how to report terrorist activities safely.',
    'message-type': 'Rewards-program intelligence appeal',
    'target-audience': 'Afghan civilians and informants',
    'call-to-action': 'Report terrorist plans or activities through the listed channels',
    'key-figures-symbols': ['Coalition officer', 'civilians', 'email address', 'rewards program'],
    'catalog-number': '155',
  },
  {
    'leaflet-code': 'AF D118',
    'operation': 'Operation Enduring Freedom',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2014',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'Syed Hussain Anwari Sima Samar Abdullah Hamid Karzai Support the interim government of Afghanistan.',
    'objective': 'Encouraging support for the interim government to ensure stability.',
    'imagery': 'Image of Afghan leaders with text urging support for the interim government.',
    'message-type': 'Political legitimation',
    'target-audience': 'Afghan civilians',
    'call-to-action': 'Support the interim government of Afghanistan',
    'key-figures-symbols': ['Hamid Karzai', 'Sima Samar', 'Abdullah Abdullah', 'Syed Hussain Anwari'],
    'catalog-number': '160',
  },
  {
    'leaflet-code': 'AF D12b',
    'operation': 'Operation Enduring Freedom',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2014',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'America has provided over $170 million in aid to Afghanistan.',
    'objective': 'The objective is to showcase the substantial aid provided by America to Afghanistan, emphasizing the significant financial assistance intended to help the Afghan people, particularly the youth.',
    'imagery': 'The leaflet shows images of Afghan children, highlighting the positive impact of American aid in Afghanistan. On the left side, Afghan children smile and look towards the camera. On the right, a man is seen with bags of aid that are clearly labeled as provided by the USA.',
    'message-type': 'Humanitarian-aid goodwill message',
    'target-audience': 'Afghan civilians',
    'call-to-action': 'Associate U.S. forces with aid delivery and relief',
    'key-figures-symbols': ['Aid sacks', 'USA marking', 'Afghan children', 'food distribution'],
    'catalog-number': '165',
  },
  {
    'leaflet-code': 'AFD85',
    'operation': 'Operation Enduring Freedom',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2014',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'Many tribes make a united Afghanistan.',
    'objective': 'This leaflet promotes national unity among Afghanistan\'s various tribes and ethnic groups, emphasizing that a united Afghanistan is stronger and more resilient.',
    'imagery': 'The leaflet features an illustration of several hands, each of a different skin tone, coming together to form the shape of Afghanistan.',
    'message-type': 'National-unity message',
    'target-audience': 'Afghan civilians across tribes and regions',
    'call-to-action': 'Build one united Afghanistan together',
    'key-figures-symbols': ['Hands', 'map of Afghanistan', 'unity motif'],
    'catalog-number': '168',
  },
  {
    'leaflet-code': null,
    'operation': 'Operation Enduring Freedom',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2014',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'No one has the right to determine the fate of your life. NATO countries help the people of Afghanistan to save themselves from the crimes of the Taliban and foreign terrorists.',
    'objective': 'To reassure the Afghan population that NATO\'s involvement is to aid in their self-determination and protect them from external threats, emphasizing the importance of their sovereignty and security.',
    'imagery': 'The leaflet features a text message stating that NATO countries are helping the people of Afghanistan to save themselves from the crimes of the Taliban and foreign terrorists.',
    'message-type': 'Protection and reassurance',
    'target-audience': 'Afghan civilians',
    'call-to-action': 'Reject Taliban violence and support international assistance',
    'key-figures-symbols': ['Green text field', 'protection message', 'Taliban referenced'],
    'catalog-number': '173',
  },
  {
    'leaflet-code': 'AFD85',
    'operation': 'Operation Enduring Freedom',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2014',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'Drop by drop becomes the sea and brick by brick becomes the house.',
    'objective': 'Encourage cooperation and unity among the Afghan people to rebuild the nation.',
    'imagery': 'Two figures in traditional Afghan attire are shown building a wall together with bricks, symbolizing collaboration. The background includes mountains.',
    'message-type': 'Reconstruction and unity message',
    'target-audience': 'Afghan civilians',
    'call-to-action': 'Work together to rebuild the country',
    'key-figures-symbols': ['Brick wall', 'handshake', 'house-building', 'proverb'],
    'catalog-number': '177',
  },
  {
    'leaflet-code': 'AFD51c',
    'operation': 'Operation Enduring Freedom',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2014',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'Who are the real administrators of the Talib regime? Mullah Omar (on leash) and Bin Laden (holding leash)',
    'objective': 'Expose the true power dynamics within the Taliban regime, showing the influence of foreign terrorists like Bin Laden over Afghan leaders.',
    'imagery': 'A figure resembling Mullah Omar is shown on a leash held by Osama bin Laden, with a map of Afghanistan underneath them.',
    'message-type': 'Anti-Taliban leadership exposure',
    'target-audience': 'Afghan civilians and Taliban rank and file',
    'call-to-action': 'See Bin Laden as the power behind Mullah Omar',
    'key-figures-symbols': ['Mullah Omar', 'Osama bin Laden', 'leash', 'Afghanistan map'],
    'catalog-number': '181',
  },
  {
    'leaflet-code': null,
    'operation': 'War on Terrorism',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2021',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'Do not touch the mines. The Danger! Mine!',
    'objective': 'The leaflet aims to warn civilians, particularly children, of the dangers of unexploded ordnance. It emphasizes the lethal risks associated with touching or playing near mines.',
    'imagery': 'A bright red triangular warning sign with a skull and crossbones, surrounded by images of various types of mines and bombs.',
    'message-type': 'Mine-awareness warning',
    'target-audience': 'Afghan civilians, especially families and children',
    'call-to-action': 'Do not touch mines or unexploded ordnance',
    'key-figures-symbols': ['Mine warning triangle', 'father and son', 'explosive devices'],
    'catalog-number': '93',
  },
  {
    'leaflet-code': 'AF D102c',
    'operation': 'War on Terrorism',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2021',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'Help the Commonwealth Nations to restore peace and stability in your country.',
    'objective': 'The objective is to encourage local support for the Commonwealth Nations\' efforts to restore peace and stability in Afghanistan. It seeks to build trust and collaboration between the coalition forces and the local population.',
    'imagery': 'The leaflet shows a coalition soldier interacting with smiling children and local families, conveying a positive image of cooperation and assistance.',
    'message-type': 'Stabilization appeal',
    'target-audience': 'Afghan civilians',
    'call-to-action': 'Support coalition-backed efforts to restore peace and stability',
    'key-figures-symbols': ['Coalition soldiers', 'Afghan children', 'relief interaction'],
    'catalog-number': '115',
  },
  {
    'leaflet-code': null,
    'operation': 'War on Terrorism',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2021',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'By attacking Afghanistan, death is inevitable for you.',
    'objective': 'The objective is to dissuade combatants from attacking Afghanistan by portraying the inevitability of death as a consequence. It seeks to instill fear and discourage hostile actions.',
    'imagery': 'The leaflet shows skulls and grim imagery to emphasize the message that attacking Afghanistan will lead to certain death.',
    'message-type': 'Threat and deterrence',
    'target-audience': 'Taliban and al-Qaeda fighters',
    'call-to-action': 'Stop attacking or face death',
    'key-figures-symbols': ['Skulls', 'red background', 'militant headgear'],
    'catalog-number': '123',
  },
  {
    'leaflet-code': 'AFG-F4-3039D',
    'operation': 'War on Terrorism',
    'conflict': 'The War in Afghanistan',
    'year': '2001-2021',
    'country-theater': 'Afghanistan',
    'languages': ['Pashto', 'Dari'],
    'translation': 'We stop your vehicles because the enemies of Afghanistan have been seen in this area. The enemies of Afghanistan have attacked the defenseless people of Afghanistan and Coalition forces. We are here to help the peace-loving people and to chase, capture or kill the criminals. If you have any information about the enemy, please inform the local Governor, local police, the Afghan National Army or Coalition forces and take part in bringing permanent peace to your country.',
    'objective': 'The objective is to justify the actions of coalition forces in stopping vehicles, ensuring the local population understands that these actions are for their safety. It encourages cooperation and reporting of any enemy activity.',
    'imagery': 'The leaflet depicts coalition forces stopping vehicles in an area where enemies of Afghanistan have been detected, with a focus on maintaining peace and security.',
    'message-type': 'Security checkpoint explanation',
    'target-audience': 'Afghan civilians and drivers',
    'call-to-action': 'Cooperate at vehicle stops and report enemy activity',
    'key-figures-symbols': ['Coalition soldier stopping vehicle', 'search scene', 'tip-off message'],
    'catalog-number': '124',
  },
];

export default leaflets;